### ISSUE TITLE
Great work. I have a question about the epe.

### ISSUE THREAD

**Issue by HFBlalalala** [andrewlstewart/StereoNet_PyTorch#1]
Great work . Thank you for your code and this implementation is closest to paper. 
I have a question about the epe : in paper, this index is 1.1. But I didn't get it when I trained other implementations in github. I wonder how to train this model and get epe like paper.
Thank you very much.

**Comment by andrewlstewart** [comment]
Hi there.  Ya, I was never able to match the authors' EPE.  It's unclear which portion of the dataset they calculate their EPE on; so it could be a bias in the test set that is causing the higher EPE.  I reached out to the two first authors but unfortunately I didn't hear back from either.  If you have any ideas or see any mistakes in the code, please let me know.  Thanks!
